#!/bin/bash
#
# copy all the stuff back to the writable NFS partition
#
# Ron Croonenberg
# 
# HPC-3 Los Alamos National Laboratory
#
#

nfs_mount="/mnt/scal-nfs"

# Make sure everything is mounted.
/bin/mount -a

#
# part one: save the configs!!
#
host_str=$(hostname)

# the /etc/scality-node directory
if [ -d "$nfs_mount/$host_str/etc-scality-node" ]; then
   /bin/rm -rf $nfs_mount/$host_str/etc-scality-node
fi
/bin/mkdir $nfs_mount/$host_str/etc-scality-node
/bin/cp -rf /etc/scality-node/* $nfs_mount/$host_str/etc-scality-node 2>/dev/null

# copy all other scality node directories
for i in `seq 1 12`; do
   if [ -d "$nfs_mount/$host_str/etc-scality-node-$i" ]; then
      /bin/rm -rf $nfs_mount/$host_str/etc-scality-node-$i
   fi
   /bin/mkdir $nfs_mount/$host_str/etc-scality-node-$i
   /bin/cp -rf /etc/scality-node-$i/* $nfs_mount/$host_str/etc-scality-node-$i 2>/dev/null
done

# /var/lib/scality-sagentd
if [ -d "$nfs_mount/$host_str/lib-scality-sagentd" ]; then
   /bin/rm -rf $nfs_mount/$host_str/lib-scality-sagentd
fi
/bin/mkdir $nfs_mount/$host_str/lib-scality-sagentd
/bin/cp -rf /var/lib/scality-sagentd/* $nfs_mount/$host_str/lib-scality-sagentd 2>/dev/null

# and now the /var/lib/scality-node
if [ -d "$nfs_mount/$host_str/lib-scality-node" ]; then
   /bin/rm -rf $nfs_mount/$host_str/lib-scality-node
fi
/bin/mkdir $nfs_mount/$host_str/lib-scality-node
/bin/cp -rf /var/lib/scality-node/* $nfs_mount/$host_str/lib-scality-node 2>/dev/null


# /etc/srebuildd.conf
#/bin/cp -f /etc/srebuildd.conf /mnt/dsu-log/$host_str/srebuildd.conf

# /etc/biziod
if [ -d "$nfs_mount/$host_str/etc-biziod" ]; then
   /bin/rm -rf $nfs_mount/$host_str/etc-biziod
fi
/bin/mkdir $nfs_mount/$host_str/etc-biziod
/bin/cp -rf /etc/biziod/* $nfs_mount/$host_str/etc-biziod

# /usr/local/scality-sagentd/modules
if [ -d "$nfs_mount/$host_str/local-sagentd/modules" ]; then
   /bin/rm -rf $nfs_mount/$host_str/local-sagentd/modules
fi
if [ ! -d "$nfs_mount/$host_str/local-sagentd" ]; then
   /bin/mkdir $nfs_mount/$host_str/local-sagentd
fi
/bin/mkdir $nfs_mount/$host_str/local-sagentd/modules
/bin/cp -rf /usr/local/scality-sagentd/modules/* $nfs_mount/$host_str/local-sagentd/modules

# /usr/local/scality-ringsh/ringsh/modules
if [ -d "$nfs_mount/$host_str/local-ringsh-ringsh/modules" ]; then
   /bin/rm -rf $nfs_mount/$host_str/local-ringsh-ringsh/modules
fi
if [ ! -d "$nfs_mount/$host_str/local-ringsh-ringsh" ]; then
   /bin/mkdir $nfs_mount/$host_str/local-ringsh-ringsh
fi
/bin/mkdir $nfs_mount/$host_str/local-ringsh-ringsh/modules
/bin/cp -rf /usr/local/scality-ringsh/ringsh/modules/* $nfs_mount/$host_str/local-ringsh-ringsh/modules


exit 0
