#!/bin/bash
#
# redirect all the Scality Supervisor directories
#
# Ron Croonenberg
# 
# HPC-3 Los Alamos National Laboratory
#
#

nfs_mount="/mnt/dsu-log"

# make sure everything is mounted
/bin/mount -a


# make sure the time is running correctly:
/sbin/service ntpd stop
/usr/sbin/ntpdate dsu-dl-master
/sbin/service ntpd start

#
# create all the directories and symbolic links
#
host_str=$(hostname)


# first fix the scality statfs bug
cd /usr/local/scality-supervisor/bin
mv ./bizstoresup ./_bizstoresup
/bin/cp /root/bizstoresup ./bizstoresup


# create config file
cd /usr/local/scality-ringsh/ringsh
/bin/rm config.py
/bin/ln -s $nfs_mount/$host_str/config.py config.py

# we're the supervisor, create our /var/log/scality-supervisor link
cd /var/log
/bin/rm scality-supervisor
/bin/ln -s $nfs_mount/$host_str/log-scality-supervisor scality-supervisor

# Create our remote dir if we don't have one
if [ ! -d $nfs_mount"/"$host_str ]; then
   /bin/cp -r $nfs_mount/dsu-dl-template $nfs_mount/$host_str
fi


# create all symbolic links in /etc for scality and also bizstorenode
# we can assume that we are in /root
cd /etc

if [ -d "scality-supervisor" ]; then										# does scality-supervisor live here?
   if [ ! -d $nfs_mount"/"$host_str"/etc-scality-supervisor" ]; then						# do we have the share already
      /bin/cp -r scality-supervisor $nfs_mount/$host_str/etc-scality-supervisor				# no ... copy it to the share
   fi
fi
/bin/rm -rf scality-supervisor											# delete initial one, always
/bin/ln -s $nfs_mount/$host_str/etc-scality-supervisor scality-supervisor					# create link to the share

# create etc-conf.d and create /etc/conf.d link
if [ ! -d $nfs_mount"/"$host_str"/etc-conf.d" ]; then
   /bin/mkdir $nfs_mount/$host_str/etc-conf.d
fi
/bin/rm -rf conf.d
/bin/ln -s $nfs_mount/$host_str/etc-conf.d conf.d

# this is a link to begin with, make sure it is pointing in the right direction
/bin/rm -rf bizstoresup												# always delete
/bin/ln -s /etc/scality-supervisor bizstoresup									# always create link

# link to sagentd.yaml
/bin/rm -rf sagentd.yaml											# always delete
ln -s $nfs_mount/$host_str/sagentd.yaml sagentd.yaml								# always create link


# go to /var/lib
cd /var/lib
if [ -d "scality-supervisor" ]; then										# does scality-supervisor lve here?
   if [ ! -d $nfs_mount"/"$host_str"/lib-scality-supervisor" ]; then						# do we have the share already
      /bin/cp -r scality-supervisor $nfs_mount/$host_str/lib-scality-supervisor				# no ... copy it to the share
   fi
fi
/bin/rm -rf scality-supervisor											# delete original always
/bin/ln -s $nfs_mount/$host_str/lib-scality-supervisor scality-supervisor					# create link to share always



if [ -d "scality-sagentd" ]; then										# does scality-sagentd live here?
   if [ ! -d $nfs_mount"/"$host_str"/lib-scality-sagentd" ]; then						# is it on the share?
      /bin/cp -r scality-supervisor $nfs_mount/$host_str/lib-scality-sagentd					# ... nope...  copy it to the share
   fi
fi
/bin/rm -rf scality-sagentd											# throw away original always
/bin/ln -s $nfs_mount/$host_str/lib-scality-sagentd scality-sagentd						# create link to the share

# copy the credentials to /tmp
/bin/cp /root/scality-installer-credentials /tmp/scality-installer-credentials

# we need to have /usr/local/scality-supervisor/supv2 in writable space
cd /usr/local/scality-supervisor
if [ -d "supv2" ]; then												# does the supv2 directory exist here? ...
   if [ ! -d $nfs_mount"/"$host_str"/supv2" ]; then								#  ... but not on the share
      /bin/cp -r /usr/local/scality-supervisor/supv2 $nfs_mount/$host_str/supv2							# copy it to the share
   fi
fi
/bin/rm -rf supv2												# delete the directory always
ln -s $nfs_mount/$host_str/supv2 supv2									# and create the link to the share


# /var/www/scality-supervisor/dsup needs to be in writable space
cd /var/www/scality-supervisor
if [ -d "dsup" ]; then												# does the dsup directory exist here? ...
   if [ ! -d $nfs_mount"/"$host_str"/www-scality-supervisor/dsup" ]; then					#  ... but not on the share
      /bin/cp -r /var/www/scality-supervisor/dsup $nfs_mount/$host_str/www-scality-supervisor/dsup		# copy it to the share
   fi
fi
/bin/rm -rf dsup												# remove the dsup dir, always
/bin/ln -s $nfs_mount/$host_str/www-scality-supervisor/dsup dsup						# and create a linkto the share


# create the /var/log/scality-supervisor link and dir
cd /var/log
if [ ! -d $nfs_mount/$host_str"/log-scality-supervisor" ]; then
   /bin/mkdir $nfs_mount/$host_str/log-scality-supervisor							# no ... copy it to the share
fi
/bin/rm -rf scality-supervisor
/bin/ln -s $nfs_mount/$host_str/log-scality-supervisor scality-supervisor

# create a /var/tmp
cd /var
if [ ! -d $nfs_mount"/"$host_str"/var-tmp" ]; then
   /bin/mkdir $nfs_mount/$host_str/var-tmp
fi
/bin/rm -rf tmp
ln -s $nfs_mount/$host_str/var-tmp tmp

# /usr/local/scality-sagentd/modules
cd /usr/local/scality-sagentd
/bin/rm -rf modules
if [ ! -d $nfs_mount"/"$host_str"/local-sagentd" ]; then
   /bin/mkdir $nfs_mount/$host_str/local-sagentd
fi
if [ ! -d $nfs_mount"/"$host_str"/local-sagentd/modules" ]; then
   /bin/mkdir $nfs_mount/$host_str/local-sagentd/modules
fi
/bin/ln -s $nfs_mount/$host_str/local-sagentd/modules modules

# /usr/local/scality-ringsh/ringsh/modules
cd /usr/local/scality-ringsh/ringsh
/bin/rm -rf modules
if [ ! -d $nfs_mount"/"$host_str"/local-ringsh-ringsh" ]; then
   /bin/mkdir $nfs_mount/$host_str/local-ringsh-ringsh
fi
if [ ! -d $nfs_mount"/"$host_str"/local-ringsh-ringsh/modules" ]; then
   /bin/mkdir $nfs_mount/$host_str/local-ringsh-ringsh/modules
fi
/bin/ln -s $nfs_mount/$host_str/local-ringsh-ringsh/modules modules


# make cwd /root again
cd ~


exit 0
