#!/bin/bash
#
# redirect all the Scality Supervisor directories
#
# Ron Croonenberg
# 
# HPC-3 Los Alamos National Laboratory
#
#

nfs_mount="/mnt/scal-nfs"

# make sure everything is mounted
/bin/mount -a


# make sure the time is running correctly:
/sbin/service ntpd stop
/usr/sbin/ntpdate sdsu-master
/sbin/service ntpd start


# Tell them this could take a while.
echo "preparing Scality disk less start ..."

# remove mod_security from apache
/bin/rm -rf /etc/httpd/conf.d/mod_security.conf
/bin/rm -rf /etc/httpd/modules/mod_security2.so

#
# create all the directories and symbolic links
#
host_str=$(hostname)


# first fix the scality statfs bug
#cd /usr/local/scality-supervisor/bin
#mv ./bizstoresup ./_bizstoresup
#/bin/cp /root/bizstoresup ./bizstoresup


# Create our remote dir if we don't have one
if [ ! -d "$nfs_mount/$host_str" ]; then
   /bin/mkdir -p $nfs_mount/$host_str
fi


# create config file
cd /usr/local/scality-ringsh/ringsh
if [ -f "config.py" ]; then
   if [ ! -f "$nfs_mount/$host_str/local-ringsh-ringsh/config.py" ]; then
      /bin/mkdir -p $nfs_mount/$host_str/local-ringsh-ringsh
      echo "/bin/cp config.py $nfs_mount/$host_str/local-ringsh-ringsh/config.py"
      /bin/cp config.py $nfs_mount/$host_str/local-ringsh-ringsh/config.py
      fi
   /bin/rm config.py
fi
/bin/ln -s $nfs_mount/$host_str/local-ringsh-ringsh/config.py config.py


# create all symbolic links in /etc for scality and also bizstorenode
cd /etc
if [ -d "scality-supervisor" ]; then										# does scality-supervisor live here?
   if [ ! -d "$nfs_mount/$host_str/etc-scality-supervisor" ]; then						# do we have the share already
      /bin/mkdir -p $nfs_mount/$host_str/etc-scality-supervisor
      echo "/bin/cp -r scality-supervisor/* $nfs_mount/$host_str/etc-scality-supervisor"
      /bin/cp -r scality-supervisor/* $nfs_mount/$host_str/etc-scality-supervisor				# no ... copy it to the share
   fi
   /bin/rm -rf scality-supervisor
fi
/bin/ln -s $nfs_mount/$host_str/etc-scality-supervisor scality-supervisor					# create link to the share

# create link for DATA-1.py in /usr/local/scality-ringsh
# to a writable DATA-1.py, DATA-1.py does not exist yet
cd /usr/local/scality-ringsh/ringsh/conf.d
if [ ! -d "$nfs_mount/$host_str/local-ringsh-ringsh/conf.d" ]; then
   /bin/mkdir -p $nfs_mount/$host_str/local-ringsh-ringsh/conf.d
   echo "/bin/touch $nfs_mount/$host_str/local-ringsh-ringsh/conf.d/DATA-1.py"
   /bin/touch $nfs_mount/$host_str/local-ringsh-ringsh/conf.d/DATA-1.py
fi
/bin/rm -rf DATA-1.py
/bin/ln -s $nfs_mount/$host_str/local-ringsh-ringsh/conf.d/DATA-1.py DATA-1.py

# /etc/bizstoresup just points at /etc/scality-supervisor which is now on nfs
cd /etc
/bin/rm -rf bizstoresup												# always delete
/bin/ln -s $nfs_mount/$host_str/etc-scality-supervisor bizstoresup						# always create link

# sagentd.yaml is on the image now
# link to sagentd.yaml  
#/bin/touch $nfs_mount/$host_str/sagentd.yaml									# create a sagentd.yaml file
#/bin/rm -rf sagentd.yaml											# always delete
#/bin/ln -s $nfs_mount/$host_str/sagentd.yaml sagentd.yaml							# always create link


# go to /var/lib/scality-supervisor
cd /var/lib
if [ -d "scality-supervisor" ]; then										# does scality-supervisor lve here?
   if [ ! -d "$nfs_mount/$host_str/lib-scality-supervisor" ]; then						# do we have the share already
      /bin/mkdir -p $nfs_mount/$host_str/lib-scality-supervisor
      echo "/bin/mkdir -p $nfs_mount/$host_str/lib-scality-supervisor"
      /bin/cp -r scality-supervisor/* $nfs_mount/$host_str/lib-scality-supervisor				# no ... copy it to the share
   fi
   /bin/rm -rf scality-supervisor
fi
/bin/ln -s $nfs_mount/$host_str/lib-scality-supervisor scality-supervisor					# create link to share always

# go to /var/lib/scality-sagentd
cd /var/lib
if [ -d "scality-sagentd" ]; then										# does scality-sagentd live here?
   if [ ! -d "$nfs_mount/$host_str/lib-scality-sagentd" ]; then							# is it on the share?
      /bin/mkdir -p $nfs_mount/$host_str/lib-scality-sagentd
      echo "/bin/cp -r scality-sagentd/* $nfs_mount/$host_str/lib-scality-sagentd"
      /bin/cp -r scality-sagentd/* $nfs_mount/$host_str/lib-scality-sagentd					# ... nope...  copy it to the share
   fi
   /bin/rm -rf scality-sagentd
fi
/bin/ln -s $nfs_mount/$host_str/lib-scality-sagentd scality-sagentd						# create link to the share

# copy the credentials to /tmp
/bin/cp /root/scality-installer-credentials /tmp/scality-installer-credentials


# we need /var/local/scality-supervisor/sprov/ to be writable on NFS
cd /var/local/scality-supervisor
if [ ! -d "$nfs_mount/$host_str/var-sprov" ]; then
   /bin/mkdir -p $nfs_mount/$host_str/var-sprov
   /bin/chown apache.apache $nfs_mount/$host_str/var-sprov
fi
/bin/rm -rf sprov
/bin/ln -s $nfs_mount/$host_str/var-sprov sprov


# we need to have /usr/local/scality-supervisor/supv2 in writable space
cd /usr/local/scality-supervisor
if [ -d "supv2" ]; then												# does the supv2 directory exist here? ...
   if [ ! -d "$nfs_mount/$host_str/supv2" ]; then								#  ... but not on the share
      /bin/mkdir -p $nfs_mount/$host_str/supv2
      echo "/bin/cp -r /usr/local/scality-supervisor/supv2/* $nfs_mount/$host_str/supv2"
      /bin/cp -r /usr/local/scality-supervisor/supv2/* $nfs_mount/$host_str/supv2					# copy it to the share
   fi
   /bin/rm -rf supv2
fi
/bin/ln -s $nfs_mount/$host_str/supv2 supv2										# and create the link to the share

# we need /usr/local/scality-supervisor/sprov ringmodel_files and solutions in writable space
if [ ! -d "$nfs_mount/$host_str/sprov/ringmodel_files" ]; then
   /bin/mkdir -p $nfs_mount/$host_str/sprov/ringmodel_files
fi
if [ ! -d "$nfs_mount/$host_str/sprov/solutions" ]; then
   /bin/mkdir -p $nfs_mount/$host_str/sprov/solutions
fi
# we have links on the image pointing to /tmp/solutions and /tmp/ringmodel_files
# to save space and prevent the whiole directory from being whitelisted.
# this is a hack/trick but should work
cd /tmp
if [ -L "/tmp/ringmodel_files" ]; then
   /bin/rm -f ringmodel_files
fi
if [ -L "/tmp/solutions" ]; then
   /bin/rm -f solutions
fi
/bin/ln -s $nfs_mount/$host_str/sprov/ringmodel_files ringmodel_files
/bin/ln -s $nfs_mount/$host_str/sprov/solutions solutions

# /var/www/scality-supervisor/dsup needs to be in writable space
cd /var/www/scality-supervisor
if [ -d "dsup" ]; then												# does the dsup directory exist here? ...
   if [ ! -d "$nfs_mount/$host_str/www-scality-supervisor/dsup" ]; then						#  ... but not on the share
      /bin/mkdir -p $nfs_mount/$host_str/www-scality-supervisor/dsup
      echo "/bin/cp -r /var/www/scality-supervisor/dsup/* $nfs_mount/$host_str/www-scality-supervisor/dsup"
      /bin/cp -r /var/www/scality-supervisor/dsup/* $nfs_mount/$host_str/www-scality-supervisor/dsup		# copy it to the share
      /bin/chown -R apache.apache $nfs_mount/$host_str/www-scality-supervisor
   fi
   /bin/rm -rf dsup
fi
/bin/ln -s $nfs_mount/$host_str/www-scality-supervisor/dsup dsup			# and create a linkto the share


# create the /var/log/scality-supervisor link and dir
cd /var/log
if [ ! -d "$nfs_mount/$host_str/log-scality-supervisor" ]; then
   /bin/mkdir -p $nfs_mount/$host_str/log-scality-supervisor							# no ... copy it to the share
fi
/bin/rm -rf scality-supervisor											# is always there
/bin/ln -s $nfs_mount/$host_str/log-scality-supervisor scality-supervisor

# create a /var/tmp
cd /var
if [ ! -d "$nfs_mount/$host_str/var-tmp" ]; then
   /bin/mkdir $nfs_mount/$host_str/var-tmp
fi
/bin/rm -rf tmp													# is always there
ln -s $nfs_mount/$host_str/var-tmp tmp

# /usr/local/scality-sagentd/modules
cd /usr/local/scality-sagentd
if [ ! -d "$nfs_mount/$host_str/local-sagentd/modules" ]; then
   /bin/mkdir -p $nfs_mount/$host_str/local-sagentd/modules
   echo "/bin/cp -r /usr/local/scality-sagentd/modules/* $nfs_mount/$host_str/local-sagentd/modules"
   /bin/cp -r /usr/local/scality-sagentd/modules/* $nfs_mount/$host_str/local-sagentd/modules
fi
/bin/rm -rf modules
/bin/ln -s $nfs_mount/$host_str/local-sagentd/modules modules

# /usr/local/scality-ringsh/ringsh/modules
cd /usr/local/scality-ringsh/ringsh
if [ ! -d "$nfs_mount/$host_str/local-ringsh-ringsh/modules" ]; then
   /bin/mkdir -p $nfs_mount/$host_str/local-ringsh-ringsh/modules
   echo "/bin/cp -r /usr/local/scality-ringsh/ringsh/modules/* $nfs_mount/$host_str/local-ringsh-ringsh/modules"
   /bin/cp -r /usr/local/scality-ringsh/ringsh/modules/* $nfs_mount/$host_str/local-ringsh-ringsh/modules
fi
rm -rf modules
/bin/ln -s $nfs_mount/$host_str/local-ringsh-ringsh/modules modules


# make cwd /root again
cd ~


exit 0
