#!/bin/bash
#
# Ron Croonenberg
#
# HPC-3 Los Alamos National Laboratory
#
# Scality diskless node prep

# chkconfig: 345 10 10
# description: Scality diskless node prep
#
# quick and dirty script to prep the machine and start/stop/restart Scality
#
. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/scality-dl-prep ]; then
. /etc/sysconfig/scality-dl-prep
fi


case "$1" in
start)
echo "Starting Scality diskless service."
/root/scality-dl-prep start
/etc/init.d/httpd start
/etc/init.d/scality-node start
/etc/init.d/scality-sagentd start
/etc/init.d/scality-sproxyd start
/etc/init.d/scality-srebuildd start
;;
stop)
echo "Stopping Scality diskless service"
#/root/scality-dl-prep stop
/etc/init.d/scality-srebuildd stop
/etc/init.d/scality-sproxyd stop
/etc/init.d/scality-sagentd stop
/etc/init.d/scality-node stop
/usr/sbin/apachectl stop
;;
restart)
#echo "Restarting Scality diskless service"
#/root/scality-dl-prep restart
/etc/init.d/scality-srebuildd stop
/etc/init.d/scality-sproxyd stop
/etc/init.d/scality-sagentd stop
/etc/init.d/scality-node stop
/usr/sbin/apachectl stop
/etc/init.d/scality-node start
/etc/init.d/scality-sagentd start
/etc/init.d/scality-sproxyd start
/etc/init.d/scality-srebuildd start
/etc/init.d/httpd start
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
;;
esac
