#!/bin/bash
#
# Ron Croonenberg
#
# HPC-3 Los Alamos National Laboratory
#
# Scality diskless node prep

# chkconfig: 345 10 10
# description: Scality diskless node prep
#
# quick and dirty script to prep the machine and start/stop/restart Scality
#

nfs_mount="/mnt/scal-nfs"

. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/scality-dl-prep ]; then
. /etc/sysconfig/scality-dl-prep
fi


case "$1" in
start)
echo "Starting Scality diskless service."

# start IRQ balance
/sbin/service irqbalance start

# disable transparent_hugepages
echo never > /sys/kernel/mm/transparent_hugepage/defrag

# check and see if scal-nfs is mounted, if not ...  try to  if fail..  abort
mounted=$(/bin/mount | grep scal-nfs | wc -l)
if [ $mounted -eq 0 ]; then
    /bin/mount $nfs_mount
    mounted=$(/bin/mount | grep scal-nfs | wc -l)
    if [ $mounted -eq 0 ]; then
       echo "Error: scal-nfs not available. Aborting..."
       exit -1
    fi
fi

# we did unload mpt2sas and reload mpt2sas after mounting nfs, because is needs some stuff.
/sbin/modprobe mpt2sas

# start scality diskless prep for this node
/root/scality-dl-prep start

# finally, start Scality
/etc/init.d/httpd start
/etc/init.d/scality-node start
/etc/init.d/scality-sagentd start
/etc/init.d/scality-sproxyd start
/etc/init.d/scality-srebuildd start
;;
stop)
echo "Stopping Scality diskless service"
#/root/scality-dl-prep stop
/etc/init.d/scality-srebuildd stop
/etc/init.d/scality-sproxyd stop
/etc/init.d/scality-sagentd stop
/etc/init.d/scality-node stop
/etc/init.d/httpd stop
;;
restart)
#echo "Restarting Scality diskless service"
#/root/scality-dl-prep restart
/usr/bin/ethcfg -c /etc/sysconfig/ethcfg-post start
/bin/mount /mnt/scal-nfs
/etc/init.d/scality-srebuildd stop
/etc/init.d/scality-sproxyd stop
/etc/init.d/scality-sagentd stop
/etc/init.d/scality-node stop
/etc/init.d/httpd stop
/etc/init.d/httpd start
/etc/init.d/scality-node start
/etc/init.d/scality-sagentd start
/etc/init.d/scality-sproxyd start
/etc/init.d/scality-srebuildd start
;;
*)
echo "Usage: $0 {start|stop|restart}"
exit 1
;;
esac
